efabless/cace

- cace/common/cace_simulate.py
Implemented code that catches ngspice dropping back to the interpreter after encountering a parse error in the input.  This prevents the severe problem of having all the simulations "lock up" and fail to respond because they are all waiting for interpreter input that will not be coming.  Unfortunately the ngspice setting "strict_errorhandling" does not work for parse errors, and until that is fixed, this somewhat hack solution is a valid workaround.
> Force ngspice exit on error

- cace/cace_gui.py
- cace/common/cace_collate.py
- cace/common/cace_regenerate.py
Added C-only parasitic extraction to the list of netlist source types from the pull-down menu at the top of the CACE GUI, and fixed an issue with new results not getting back into the datasheet when a parameter has one result already and the netlist type has changed.
> Fixed adding results after netlist type is changed.

- cace/common/cace_gensim.py
- cace/common/layout_estimate.py
- cace/common/netlist_precheck.py
Changed python "eval()" to "ast.literal_eval()" in all occurrences where it is used to evaluate expressions used in testbench schematics.  The intention was for eval() to resolve simple mathematical expressions, not to execute any general-purpose python code, and the use of the "safe" evaluation will prevent any accidental or malicious use of python code embedded in CACE testbenches.
> Changed python "eval()" to "ast.literal_eval()" for security reasons.

- cace/common/cace_gensim.py
- cace/common/layout_estimate.py
- cace/common/netlist_precheck.py
Reverts efabless/cace#18.  The solution may have once been valid but not since python 3.7, making it useless for CACE.  There is a workaround that I will apply instead after reverting this change.
> Revert "Changed python "eval()" to "ast.literal_eval()" for security reasons."

- cace/cace_gui.py
Removed the "User:" line from the top of the GUI window.  This was only meaningful in the Open Galaxy implementation, and now just causes errors with setups that do not declare a USER environment variable.
> Removed the "User:" line from the top of the GUI window.

- cace/common/cace_regenerate.py
Corrected an error in which, when CACE cannot find the specified schematic file, it reports the netlist as the file that cannot be found, which makes it hard to figure out what the actual problem is.
> Corrected error message for missing schematic.

- .github/workflows/ci.yaml
- Makefile
This PR sets up our initial CI to lint cace, build cace and simply run `cace -help`.
Note that #19 should be merged first.
> Create initial CI

- cace/cace_gui.py
Disabled the use of os.setpgid(), which is at best not working and at worst causing errors on some systems.  Will need to find another method for canceling ongoing simulations.  Also fixes a small error when setting button text from "(in progress)" back to "Simulate".
> Disabled the use of os.setpgid()

- .github/workflows/pypi.yaml
This workflow only runs on pushes to `main` in this repository if `cace/__version__.py` was touched.
> Add workflow for publishing to PyPI

- cace/cace_gui.py
- cace/common/cace_regenerate.py
Fixed the position of the code that sets the current working directory so that it always happens directly after reading a new datasheet, so that behavior is always consistent relative to the definition of the root path.  Also:  Fixed a typo that can cause a failure in the netlist regeneration.
> Fixed the setting of the current directory after reading a datasheet

- cace/__version__.py
- cace/cace_cli.py
Fixed a problem that occurs in multithreading scheduling when only one of the sections "electrical-parameters" or "physical-parameters" is present (also if neither is present).  The code was making the assumption that both exist and was looking for a list of two results.
> Fixed problem when parameter sections are not both defined.

- cace/__version__.py
- cace/common/cace_makeplot.py
- cace/gui/editparam.py
- cace/gui/failreport.py
Plotting over any stepped condition was known to be semi-broken after porting to off-platform;  testbenches were all merged together and the stepping was lost.  This has been corrected.  Plots can be made with any variable condition on the X-axis and will display the results over all other condition groups as additional curve traces in the same graph, with the key text corresponding to the unique set of conditions.
> Fix plot steps

- cace/__version__.py
- cace/common/cace_read.py
- cace/common/cace_regenerate.py
Corrected "cace_read.py" to treat dependencies as a list of dictionaries, which it was supposed to (any example having more than one dependency would have shown this to be broken).  Modified "cace_regenerate.py" to check for *local* dependencies in the dependency list, which is dependencies inside the project.  This allows schematics to be spread across multiple directories.  Also, each dependency path is checked for an "xschem" subdirectory, but if that does not exist, then the dependency path itself is used. Any project can potentially set up xschem to find all of its files from one of these path choices.
> Added support for local dependencies

- cace/__version__.py
- cace/common/cace_makeplot.py
- cace/doc/format.txt
- docs/source/formats/format_description.md
Added to the "type" values understood by the "plot" dictionary to include "semilogx", "semilogy", and "loglog", corresponding to the plot types of the same name in Matlab/octave/matplotlib.
> Added "semilogx", "semilogy", and "loglog" to plot types.

- cace/cace_gui.py
cace-gui crash on windows with:
AttributeError: module 'signal' has no attribute 'SIGUSR1'
It seems that ignoring the instruction fix the issue.
I don't know the purpose of SIGUSR1 so maybe I miss something.
> ignore SIGUSR1 on windows

- cace/__version__.py
- cace/common/cace_launch.py
Removed the 300 second timout from the result.get() call that merges threads from multiprocessing.  The timeout itself causes the process to hang, so all it accomplishes is to prevent any simulations from taking longer than 300 seconds to run.
> Removed the 300 second timout for thread completion

- .github/workflows/ci.yaml
- cace/cace_cli.py
- cace/cace_gui.py
- cace/common/cace_write.py
- docs/source/usage/cace_cli.md
- docs/source/usage/getting_started.md
This PR simplifies argument parsing by using the builtin module `argparse`
- cace: Allows to specify a list of parameters
`cace cace/sky130_ef_ip__instramp.txt -s schematic --summary --parameter Idd_enabled psrr_100k `
- cace-gui: captures console output only if `--terminal` is passed (not even for a short time)
This is in preparation for the multiprocessing rewrite.
> Use argparse for argument parsing

- cace/__version__.py
- cace/common/cace_makeplot.py
- cace/common/cace_write.py
Fixed two issues deemed "severe":
(1) cace_makeplot overwrites a "results" dictionary in a parameter,
destroying min/typ/max values.  This happens when testbench
simulation data are inspected by plotting them.
(2) cace_write writes the value of paths['root'] which is always
'.' when it should be the location of the cwd relative to the
location chosen for the output file.
> Fixed two issues deemed "severe"

- Changelog.md
- cace/__version__.py
- cace/cace_gui.py
- cace/common/simulation_manager.py
Instead of printing an error message *and* crashing, just print the error message and exit.
> GUI: exit when no datasheet is found

- cace/__version__.py
- pyproject.toml
This makes it possible to package CACE with nix.
Fixes #58
> Lower setuptools_scm requirements to >=7

- Changelog.md
- cace/__version__.py
- cace/cace_gui.py
- cace/common/electrical_parameter.py
- cace/common/physical_parameter.py
- cace/common/simulation_job.py
- cace/common/simulation_manager.py
Follow-up to #48
There are now two lists for queued and running parameters protected by locks.
All in all the code was cleaned up and queued parameters can now also be cancelled.
In addition, the netlist source can no longer be changed when parameters are running.
Fixes: #50 #51
> Scheduling improvements for parameters

- .github/actions/build_nix/action.yml
- .github/actions/check_space/action.yml
- .github/actions/setup_env/action.yml
- .github/workflows/ci_nix.yml
- cace/open_pdks_rev
- default.nix
- flake.lock
- flake.nix
- nix/colab-env.nix
- nix/create-shell.nix
- nix/docker.nix
- requirements.txt
- shell.nix
This PR adds [Nix](https://nixos.org/) as build system for CACE to easily install all dependencies.
A wide range of packages are already available from [nixpkgs](https://github.com/NixOS/nixpkgs). Yet, we also have our own flake [nix-eda](https://github.com/efabless/nix-eda) with a collection of Nix derivations for common EDA tools used at Efabless.
This PR is still WIP:
> WIP: Nix build system

- Changelog.md
- cace/__version__.py
- cace/cace_cli.py
- cace/common/cace_write.py
- cace/common/simulation_manager.py
This PR adds a Markdown summary. The short summary is always printed to stdout at the end of `cace-cli`. In addition, a summary file is created by passing a file path to `--summary`.
<details><summary>
View Summary
</summary>
**general**
- name: sky130_ef_ip__instramp
- description: Rail-to-rail driver instrumentation amplifier
- commit: N/A
- PDK: sky130A
- cace_format: 4.0
**authorship**
- designer: Tim Edwards
- company: Efabless Corporation
- creation_date: January 5, 2024
- license: Apache 2.0
**netlist source**: schematic
|      Parameter       |      Testbench       | Min Limit  |  Min Value   | Typ Target |  Typ Value   | Max Limit  |  Max Value   |  Status  |
| :------------------- | :------------------- | ---------: | -----------: | ---------: | -----------: | ---------: | …
> Add a Markdown summary

- Changelog.md
- cace/__version__.py
- cace/common/electrical_parameter.py
- cace/common/simulation_job.py
- cace/gui/consoletext.py
Reenables `--sequential` for CLI and "Simulate single-threaded" for GUI.
> Restore functionality of `sequential` runtime option

- Changelog.md
- cace/__version__.py
- cace/cace_cli.py
- cace/cace_gui.py
- cace/common/cace_collate.py
- cace/common/cace_read.py
- cace/common/cace_write.py
- cace/common/simulation_job.py
- cace/common/simulation_manager.py
- cace/gui/rowwidget.py
- cace/gui/settings.py
Make YAML the new default datasheet format, remove support for JSON format.
- When searching for the datasheet, `.yaml` is preferred over `.txt`.
- When saving a datasheet, `.yaml` is the default extension.
After loading a YAML datasheet the internal datastructure should be identical to the one loaded from a text file. Exception: In the "pins" section, Vmax and Vmin are now just a string instead of a list, e.g. `dvdd - 0.3`.
> Add support for new YAML datasheet format

- Changelog.md
- cace/__version__.py
- cace/common/cace_gensim.py
For example, the following line: `.lib /home/leo/.volare/sky130A/libs.tech/combined/sky130.lib.spice {corner}`
Throws the following warnings:
```
Warning: This path may not be portable: /home/leo/.volare/sky130A/libs.tech/combined/sky130.lib.spice
Reason: Contains "libs.tech" or "libs.ref" but {PDK_ROOT} is missing
```
```
Warning: This path may not be portable: /home/leo/.volare/sky130A/libs.tech/combined/sky130.lib.spice
Reason: Starts with the user's home directory
```
At the moment the warnings get a little lost in all the output. That's why I want to work on reworking the messaging system next.
Fixes #71
> Add portability checks for paths

- Changelog.md
- cace/__version__.py
- cace/cace_cli.py
- cace/common/cace_makeplot.py
- cace/common/cace_regenerate.py
Schematic netlist is always generated to get the correct port order for the extracted netlists
> Improve netlist generation

- Changelog.md
- cace/__version__.py
- cace/parameter/electrical_parameter.py
- cace/parameter/parameter_manager.py
Do not generate testbench netlists in parallel, this leads to race conditions.
> Do not generate testbench netlists in parallel

- Changelog.md
- cace/__version__.py
- cace/cace_cli.py
- cace/cace_gui.py
- cace/common/cace_makeplot.py
- cace/parameter/electrical_parameter.py
- cace/parameter/parameter.py
- cace/parameter/parameter_manager.py
- cace/parameter/physical_parameter.py
- cace/parameter/simulation_job.py
- docs/source/usage/cace_cli.md
This PR implements the `-j`/`--jobs` argument to limit the maximum number of jobs run in parallel.
By default the jobs are equal to the number of cores.
> Implement `--jobs` argument

- Changelog.md
- cace/__version__.py
- cace/cace_cli.py
- cace/cace_gui.py
- cace/parameter/parameter_manager.py
- docs/source/usage/cace_cli.md
- Added `--max-runs` to both the CLI and GUI to limit the maximum number of runs in the run folder
- Print the total runtime after completion of the CLI run
> Add `--max-runs` argument and print total runtime

- Changelog.md
- cace/__version__.py
- cace/common/cace_write.py
- cace/parameter/parameter.py
- cace/parameter/parameter_ngspice.py
If a conditions does not exist, do not replace the placeholder. For example, if the xschem template contains `\{ib\}` and `ib` is not a condition in CACE, leave it as is.
> Substitution Improvement

- Changelog.md
- cace/__version__.py
- cace/common/cace_read.py
- cace/common/cace_regenerate.py
- cace/parameter/parameter.py
- docs/source/reference_manual/template_format.md
- **New format for CACE substitutions**
- `CACE{condition}` and `CACE[expression]`
- Fallback for datasheet version <= 5.0
- Export the schematic netlist with `top_is_subckt` enabled, which preserves certain spice parameters. This improves the simulation accuracy compared to layout extracted.
- Fix for layout extraction: Reload the top cell after `readspice`
Documentation: Reference manual was updated.
> New substitution format and other improvements

- Changelog.md
- cace/__version__.py
- cace/parameter/parameter_magic_area.py
- cace/parameter/parameter_magic_drc.py
Use absolute path to access the layout as the parameters are started from the `run/` directory.
> Use absolute path for layout

- Changelog.md
- cace/__version__.py
- cace/common/cace_regenerate.py
- cace/common/cace_write.py
- cace/common/common.py
- cace/parameter/parameter_manager.py
- Improve netlist regeneration:
- Call `extract no all` when netlist source is layout
- Use correct layout image names when GDS is compressed
- Don't crash when GDS layout is not found
> Improve layout regeneration

- Changelog.md
- cace/__version__.py
- cace/parameter/__init__.py
- cace/parameter/parameter_magic_antenna_check.py
- cace/parameter/parameter_magic_drc.py
- docs/source/reference_manual/tools.md
- Add `magic_antenna_check` as a tool
- Performs antenna violation checks using magic
- Returns `antenna_violations`, the number of violations that have occured
Example datasheet entry:
```yaml
magic_antenna_check:
description: Run antenna violation check using magic
display: Antenna Checks
spec:
antenna_violations:
maximum:
value: 0
tool:
magic_antenna_check
```
> Implement `magic_antenna_check` tool

- Changelog.md
- cace/__version__.py
- cace/cace_cli.py
- cace/parameter/parameter_manager.py
- docs/source/reference_manual/datasheet_format.md
- docs/source/usage/cace_cli.md
- Add `runs` path to datasheet
- Specifies where the `runs` directory will be created
- Add `--run-path` to arguments
- Overrides `runs` path from datasheet
Example datasheet entry:
```yaml
paths:
root:             ..
schematic:        xschem
layout:           gds
netlist:          netlist
documentation:    docs
runs:             _runs
```
Fixes #110 
Should be merged after #112
> Add `runs` path to datasheet

- Changelog.md
- cace/__version__.py
- cace/parameter/parameter.py
- docs/source/reference_manual/datasheet_format.md
- Implement plot limits
- Plots have an optional argument `limits`, which can be `true`, `false` or `auto`
Example entry:
```yaml
plot:
gain_vs_temp:
type: xyplot
xaxis: temperature
yaxis: a0
limits: true
ugf_vs_corner:
type: xyplot
xaxis: corner
yaxis: ugf
limits: false
pm_vs_vdd:
type: xyplot
xaxis: vdd
yaxis: pm
limits: auto
```
Fixes #111
> Implement plot limits

- default.nix
- flake.lock
- flake.nix
- nix/gdsfactory.nix
This PR ships gdsfactory with KLayout to enable the use of the KLayout Pcells in [sky130_klayout_pdk](https://github.com/efabless/sky130_klayout_pdk).
- update `nix-eda`
- add a Nix config to build gdsfactory (`./nix/gdsfactory.nix`)
- add `klayout-gdsfactory` to cace
> Ship gdsfactory with KLayout

- Changelog.md
- cace/__version__.py
- cace/cace_cli.py
- Allow parameters to be specified via `--parameter` as a pattern
- Add `--skip-parameter` to skip certain parameters
- Applied after parameters have been queued via `--parameter`
- Also allows the use of patterns
[fnmatch](https://docs.python.org/3/library/fnmatch.html) is used for pattern matching.
Resolves #125
- To run all parameters starting with `klayout` run: `cace -p klayout*`
- To run all parameters except those starting with `klayout` run: `cace -sp klayout*`
- To run all parameters starting with `klayout` except `klayout_drc_full` run: `cace -p klayout* -sp klayout_drc_full`
> Queue and skip parameters via pattern matching

- Changelog.md
- cace/__version__.py
- cace/parameter/parameter_ngspice.py
This PR creates a summary for the simulation runs of a parameter using the `ngspice` tool.
CACE saves the summary as `simulation_summary.md` in the parameter directory and prints a rendered version.
The first column contains the run number, the following columns contain the changing conditions, and the last columns contain the results, which may look as follows:
```
run        b   corner   temperature    vout   offset_error  
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 
run_00    25       ss           -40   0.334      3.693e-03  
run_01   230       ss           -40   3.299          0.101  
run_02    25       tt           -40   0.335      3.749e-03  
run_03   230       tt           -40   3.300          0.102  
run_04    25       ff           -40   0.335      3.809e-03 …
```
> Add runs summary as Markdown table
