efabless/cace

cace_regenerate.py

CACE now automatically clones listed dependencies which do not exist.

Add dependency handling

---

cace_gui.py
cace_write.py
settings.py

Added the ability to export a datasheet in HTML format.  Also, restored the "Save as" and "Load" functions, which had been hidden in a "settings" option and had become unreachable with the related setting was removed from the code.

Added ability to export a datasheet in HTML format.

---

cace/common/cace_regenerate.py

Modified cace_regenerate.py (again) to generate a primitive version of the schematic symbol in the testbench directory.  Along with not attempting to set an xschem path for the schematic, this prevents multiple definitions of the subcircuit while allowing the subcircuit netlist to be substituted from the proper schematic or layout source, as intended.

Automatic generation of primitive symbol in testbench directory

---

Makefile
README.md
cace/__init__.py
cace/__version__.py
cace/common/cace_evaluate.py
docs/source/conf.py
pyproject.toml
requirements.txt
requirements_dev.txt
requirements_docs.txt

This PR fixes some of the issues we has since we transitioned to a Python package.
Since it does not contain any new features and just fixes things, this can be merged as is.
- Fixes run all simulations
- One version number to rule them all (`cace/__version__.py`)
- Specified versions of dependencies

Fix issues after transitioning to package

---

cace/cace_gui.py
cace/gui/failreport.py

Corrected units handling in the failure report window, so that results are shown in the correct units, and failures are marked red for values in the correct units.

Corrected units handling in the failure report window

---

cace/gui/editparam.py

Fixed the parameter editor window, which had not been updated from the original platform version.

Fixed the parameter editor window

---

.gitignore
cace/__version__.py
pyproject.toml
requirements.txt

Add pillow to the requirements and set the minimum version.
Also, dynamically load the `requirements.txt` from `pyproject.toml` to prevent duplication.
Again, since this only contains fixes, I am going to merge this and upload a new package to PyPI.

Add pillow to requirements

---

cace/__version__.py
requirements.txt

Lower package requirements to be compatible with Python 3.8

---

cace/common/cace_write.py

Added generation of an SVG plot from xschem to add a picture of the schematic symbol of the circuit to the HTML output file.

Added SVG plot of symbol to HTML output

---

.github/workflows/ci.yaml
Makefile
README.md
docs/source/index.rst
docs/source/usage/getting_started.md

Update the README and the docs.

Update the Documentation

---

cace/cace_gui.py
cace/common/cace_read.py
cace/common/cace_write.py
cace/gui/failreport.py

Bug fixes:
1) HTML, fixed SVG generation, which was running in the wrong path 2) Fixed failure to set netlist source on "Load"
3) Fixed modification date not being interpreted as a string 4) HTML fixed error printing dependencies
Enhancements:
1) Fail report now lists the names of testbenches for help debugging 2) HTML report now shows failing parameters in red

Miscellaneous fixes and enhancements:

---

cace/__version__.py

Update version (should have been done with the last push---I'm still getting used to this).

Update version to 2.1.7

---

cace/__version__.py
cace/common/cace_makeplot.py

Corrected the reshaping of a result vector for plotting against a condition when only one result is given per testbench (result is a single floating-point value, not a list).

Corrected plotting against a condition when there is only one result per testbench.

---

Changelog.md
README.md
cace/__version__.py
cace/cace_cli.py
cace/cace_gui.py
cace/common/cace_evaluate.py
cace/common/cace_makeplot.py
cace/common/cace_regenerate.py
cace/common/cace_simulate.py
cace/common/electrical_parameter.py
cace/common/physical_parameter.py
cace/common/simulation_job.py
cace/common/simulation_manager.py
cace/gui/consoletext.py
cace/gui/editparam.py
cace/gui/failreport.py
cace/gui/rowwidget.py
cace/gui/settings.py
cace/gui/simhints.py
cace/gui/style.py
cace/gui/textreport.py

This PR is still a work in progress. During restructuring, I definitely broke a few things.
Needs testing/more work:
Known issues:
- Race condition: in rare cases sim all button does not go back to "Simulate All"
- Bug: a queued but not yet processed simulation can not be cancelled
- Bug: Opening the report/plot for a canceled simulation which previously completed fails
Future work:
- Reports: Create subdirectories for schematic/layout/pex/rcx
- Retrigger calculations when new limits are set

Multiprocessing rewrite

---

Changelog.md
cace/__version__.py
cace/cace_cli.py
cace/cace_gui.py

Add the `--version` argument to both the CLI and GUI.

Add `--version` argument

---

Changelog.md
cace/__version__.py
cace/common/cace_regenerate.py

- If a magic path is given, check whether the file actually exists.
- Uses `readspice` to get the port order for the spice netlist.

Improve extraction from GDS

---

Changelog.md
cace/__version__.py
cace/cace_cli.py
cace/cace_gui.py
cace/common/cace_write.py
cace/common/electrical_parameter.py
cace/common/simulation_job.py
cace/common/simulation_manager.py
cace/gui/rowwidget.py
default.nix
requirements.txt

This PR uses [Rich](https://github.com/Textualize/rich)  to add a progress bar and render the Markdown of the summary.
Also reorders some functions in the GUI to fix #72.
Passes `--batch` to ngspice to exit simulations on error.

Add progress bar and render Markdown + pass `--batch` to ngspice

---

Changelog.md
cace/__version__.py
cace/common/cace_regenerate.py
cace/parameter/parameter.py

- Improve plots
- Sort minimum/typical/maximum labels
- Connect points with the same condition on the x-axis
- Print when netlists do not need regeneration

Improve plot output

---

Changelog.md
cace/__version__.py
cace/common/cace_regenerate.py
cace/common/common.py
cace/parameter/parameter_klayout_drc.py
cace/parameter/parameter_magic_area.py
cace/parameter/parameter_magic_drc.py

- Improve layout detection
- Fix `.gds.gz` handling
- Unify codepaths for layout detection
- Unify log messages during regeneration
Tested with:
- `.gds` root layout
- `.gds.gz` root layout
- `.mag` root layout

Improve layout detection

---

Changelog.md
cace/__version__.py
cace/common/cace_read.py
cace/common/cace_regenerate.py
cace/parameter/parameter_magic_area.py
cace/parameter/parameter_magic_drc.py

- Use `path search +path` in magic

Use "path search +path" in magic

---

Changelog.md
cace/__version__.py
cace/common/cace_regenerate.py

Generate a gzip compressed GDS file from magic layout

Compress GDS

---

Changelog.md
cace/__version__.py
cace/common/cace_write.py

- Fix: Do not include broken links in the documentation if no layout is available
Fixes #104

Do not add broken links to the documentation

---

Changelog.md
cace/__version__.py
cace/parameter/parameter_ngspice.py
docs/source/reference_manual/template_format.md

- Add reserved variable `netlist_source`
Fixes #129 
To be discussed.

Add `netlist_source` as reserved variable

---

cace/common/cace_regenerate.py

This PR makes it possible to include other spice files into the project schematic.
That is useful if the actual device parameters for sizing are in a different file. Note that the relative path still needs to be converted to an absolute path using tcl in order for ngspice to find the file when executed in the run directory.

Set pwd to schematic dir when invoking xschem
